# Generated by Django 5.1.6 on 2025-02-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Alumne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('cognom1', models.CharField(max_length=100)),
                ('cognom2', models.CharField(blank=True, max_length=100, null=True)),
                ('correu', models.EmailField(max_length=254)),
                ('curs', models.CharField(max_length=50)),
                ('moduls', models.ManyToManyField(blank=True, related_name='alumnes', to='Centre.module')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('cognom1', models.CharField(max_length=100)),
                ('cognom2', models.CharField(blank=True, max_length=100, null=True)),
                ('correu', models.EmailField(max_length=254)),
                ('curs', models.CharField(max_length=50)),
                ('tutor', models.BooleanField(default=False)),
                ('moduls', models.ManyToManyField(blank=True, related_name='professors', to='Centre.module')),
            ],
        ),
    ]
